public enum TokenType {
    IDENTIFIER, KEYWORD, CONSTANT, OPERATOR, ERROR, EQUALITY_OPERATOR, ASSIGNMENT_OPERATOR,
    LESS_THAN_OR_EQUAL, LESS_THAN, GREATER_THAN_OR_EQUAL, GREATER_THAN, INCREMENT_OPERATOR,
    ARITHMETIC_OPERATOR, DECREMENT_OPERATOR, LEFT_PAREN, RIGHT_PAREN, COLON, SEMICOLON, NAME,
    MODULE , BEGIN, END, INTEGER, REAL, CHAR, PROCEDURE, CONST, VAR, COLON_ASSIGNMENT_OPERATOR,
    READINT , READREAL,READCHAR,READLN, WRITEINT,WRITECHAR,WRITEREAL,WRITELN,COMMA, EOF ,
    IF, THEN, ELSEIF, ELSE, WHILE, DO, LOOP, UNTIL, EXIT, CALL ,NOT_EQUAL,MOD,DIV,MUL,DIVISION
}